name: args
version: 0.12.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
documentation: http://api.dartlang.org/docs/pkg/args
description: >
 Library for defining parsers for parsing raw command-line arguments into
 a set of options and values using GNU and POSIX style options.

dependencies:
  collection: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.11.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
