name: glob
version: 1.0.1-dev
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: Bash-style filename globbing.
dependencies:
  path: ">=1.0.0 <2.0.0"
  string_scanner: ">=0.1.0 <0.2.0"
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
  scheduled_test: ">=0.11.2 <0.12.0"
