name: dart2wasm
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
environment:
  sdk: '>=2.12.0'

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  _js_interop_checks: any
  front_end: any
  kernel: any
  vm: any
  wasm_builder: any
