name: telemetry
description: A library to facilitate reporting analytics and crash reports.
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=1.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  meta:
    path: ../meta
  path: ^1.4.0
  stack_trace: ^1.7.0
  usage: ^3.2.0+1

dev_dependencies:
  test: ^1.0.0
