name: docgen
author: Dart Team <misc@dartlang.org>
description: A documentation generator for the Dart repository.
homepage: https://www.dartlang.org/
dependencies:
  args: '>=0.9.0 <0.13.0'
  logging: '>=0.9.0 <0.10.0'
  markdown: 0.7.0
  path: '>=0.9.0 <2.0.0'
  yaml: '>=0.9.0 <3.0.0'
dev_dependencies:
  scheduled_test: '>=0.10.0 <0.12.0'
  unittest: '>=0.9.0 <0.12.0'
