name: docgen
version: 0.9.2-dev
author: Dart Team <misc@dartlang.org>
description: A documentation generator for the Dart repository.
homepage: https://github.com/dart-lang/dartdoc-viewer
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.11.0'
  logging: '>=0.9.0 <0.10.0'
  markdown:
    git:
      ref: emilysEdits
      url: https://github.com/efortuna/dart-markdown
  path: '>=0.9.0 <2.0.0'
  yaml: '>=0.9.0 <0.10.0'
dev_dependencies:
  scheduled_test: '>=0.10.0 <0.11.0'
  unittest: '>=0.9.0 <0.11.0'
