name: vm
description: VM specific Dart code and helper scripts
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.0.0
  build_integration:
    path: ../build_integration
  crypto: any
  front_end:
    path: ../front_end
  kernel:
    path: ../kernel
  package_config: any
  collection: ^1.15.0

dev_dependencies:
  expect:
    path: ../expect
  json_rpc_2: any
  path: any
  test: any
  web_socket_channel: any
