name: vm
description: VM specific Dart code and helper scripts
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: ^3.7.0

resolution: workspace

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  args: any
  build_integration: any
  collection: any
  crypto: any
  front_end: any
  kernel: any
  package_config: any
  path: any
  record_use: any
  yaml: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  dart2wasm: any
  expect: any
  json_rpc_2: any
  lints: any
  test: any
  web_socket_channel: any
