name: native_compiler
description: Compiler targeting native platforms
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  cfg: any
  kernel: any

dev_dependencies:
  front_end: any
  test: any
  vm: any
