name: dartdev

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  analysis_server: any
  analysis_server_client: any
  analyzer: any
  args: any
  cli_util: any
  collection: any
  dart2native: any
  dart_style: any
  dartdoc: any
  dds: any
  front_end: any
  logging: any
  meta: any
  native_assets_builder: any
  native_assets_cli: any
  package_config: any
  path: any
  pub: any
  telemetry: any
  unified_analytics: any
  usage: any
  vm: any
  yaml: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  expect: any
  lints: any
  pub_semver: any
  test: any
