name: observatory
version: 1.6.0-dev.1
dependencies:
  args: any
  polymer: any
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/index_devtools.html
- $dart2js:
    suppressWarnings: false
    $exclude: web/main.dart
