name: shelf_web_socket
version: 0.0.1+1
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A WebSocket handler for Shelf.
dependencies:
  http_parser: ">=0.0.2 <0.1.0"
  shelf: ">=0.5.2 <0.6.0"
dev_dependencies:
  http: ">=0.10.0 <0.12.0"
  unittest: ">=0.10.0 <0.12.0"
environment:
  sdk: ">=1.4.0-dev.5.0 <2.0.0"
