# This pubspec is currently mainly used to make it easier to develop on the
# gardening by making it a package.
name: gardening
#version: do-not-upload
dependencies:
  args:
  expect:
    path: ../../pkg/expect/
  testing:
    path: ../../pkg/testing/