name: matcher
version: 0.11.3+1
author: Dart Team <misc@dartlang.org>
description: Support for specifying test expectations
homepage: https://pub.dartlang.org/packages/matcher
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
