name: matcher
version: 0.10.1
author: Dart Team <misc@dartlang.org>
description: Support for specifying test expectations
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://api.dartlang.org/docs/pkg/matcher
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
