name: collection
version: 0.9.3+1
author: Dart Team <misc@dartlang.org>
description: Collections and utilities functions and classes related to collections.
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.11.0'
