name: typed_data
version: 1.0.0
author: Dart Team <misc@dartlang.org>
description: Utility functions and classes related to the 'dart:typed_data' library.
homepage: http://www.dartlang.org
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.5.0 <2.0.0"
