name: polymer
version: 0.9.2+3
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  analyzer: ">=0.10.1 <0.11.0"
  args: ">=0.9.0 <0.10.0"
  barback: ">=0.9.0 <0.11.0"
  browser: ">=0.9.0 <0.10.0"
  csslib: ">=0.9.0 <0.10.0"
  custom_element: ">=0.9.1+1 <0.10.0"
  html5lib: ">=0.9.1 <0.10.0"
  html_import: ">=0.9.0 <0.10.0"
  logging: ">=0.9.0 <0.10.0"
  observe: ">=0.9.1 <0.10.0"
  path: ">=0.9.0 <2.0.0"
  polymer_expressions: ">=0.9.1 <0.10.0"
  shadow_dom: ">=0.9.1 <0.10.0"
  source_maps: ">=0.9.0 <0.10.0"
  template_binding: ">=0.9.0 <0.10.0"
  yaml: ">=0.9.0 <0.10.0"
transformers:
- observe:
    files: lib/src/instance.dart
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
