name: polymer
version: 0.11.0-dev.7
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  analyzer: '>=0.15.6 <0.16.0'
  args: '>=0.10.0 <0.12.0'
  barback: '>=0.9.0 <0.15.0'
  browser: '>=0.10.0 <0.11.0'
  code_transformers: '>=0.1.4 <0.2.0'
  html5lib: '>=0.11.0 <0.12.0'
  logging: '>=0.9.0 <0.10.0'
  observe: '>=0.10.0 <0.11.0'
  path: '>=0.9.0 <2.0.0'
  polymer_expressions: '>=0.11.0 <0.12.0'
  smoke: '>=0.1.0 <0.2.0'
  source_maps: '>=0.9.0 <0.10.0'
  template_binding: '>=0.11.0-dev <0.12.0'
  web_components: '>=0.3.5-dev <0.4.0'
  yaml: '>=0.9.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
transformers:
- polymer/src/build/mirrors_remover:
    $include: lib/polymer.dart
- observe:
    files: lib/src/instance.dart
    $include: lib/src/instance.dart
environment:
  sdk: '>=1.4.0 <2.0.0'
