name: polymer
version: 0.15.0+1
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  analyzer: '>=0.15.6 <0.23.0'
  args: '>=0.11.0 <0.13.0'
  barback: '>=0.14.2 <0.16.0'
  browser: '>=0.10.0 <0.11.0'
  code_transformers: '>=0.2.3 <0.3.0'
  html5lib: '>=0.12.0 <0.13.0'
  logging: '>=0.9.2 <0.10.0'
  observe: '>=0.11.0 <0.13.0'
  path: '>=0.9.0 <2.0.0'
  polymer_expressions: '>=0.12.0 <0.14.0'
  smoke: '>=0.2.0 <0.3.0'
  source_maps: '>=0.9.4 <0.11.0'
  source_span: '>=1.0.0 <2.0.0'
  template_binding: '>=0.12.0 <0.14.0'
  web_components: '>=0.7.0 < 0.9.0'
  yaml: '>=0.9.0 <3.0.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
  markdown: '>=0.7.0 <0.8.0'
transformers:
- polymer/src/build/mirrors_remover:
    $include: lib/polymer.dart
- polymer/src/build/delete_file:
    $include:
      - lib/src/build/log_injector.css
      - lib/src/js/polymer/polymer.concat.js
      - lib/src/js/polymer/polymer.concat.js.map
      - lib/src/js/polymer/polymer.js.map
- polymer/src/build/remove_sourcemap_comment:
    $include: lib/src/js/polymer/polymer.js
- observe:
    files: lib/src/instance.dart
    $include: lib/src/instance.dart
environment:
  sdk: '>=1.4.0 <2.0.0'
