name: observe
version: 0.9.0
author: Web UI Team <web-ui-dev@dartlang.org>
description: >
  Observable properties and objects for use in Model-Driven-Views (MDV).
  MDV extends HTML and the DOM APIs to support a sensible separation between the
  UI (DOM) of a document or application and its underlying data (model).
  Updates to the model are reflected in the DOM and user input into the DOM is
  immediately assigned to the model.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  analyzer: ">=0.10.1 <0.11.0"
  barback: ">=0.9.0 <0.10.0"
  logging: ">=0.9.0 <0.10.0"
  path: ">=0.9.0 <0.10.0"
  source_maps: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
