name: analysis_server_client
version: 1.1.3
description:
  A client wrapper over analysis_server.
  Instances of the class [Server] manage a connection to a server process,
  and facilitate communication to and from the server.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server_client
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  path: ^1.7.0
  pub_semver: ^1.4.4
dev_dependencies:
  analyzer:
    path: ../analyzer
  analysis_server:
    path: ../analysis_server
  analyzer_utilities:
    path: ../analyzer_utilities
  test: ^1.14.2
