name: analysis_server_client
version: 1.1.3
description:
  A client wrapper over analysis_server.
  Instances of the class [Server] manage a connection to a server process,
  and facilitate communication to and from the server.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server_client
environment:
  sdk: '>=2.1.0-dev.9.0 <3.0.0'
dependencies:
  path: ^1.6.2
  pub_semver: ^1.4.2
dev_dependencies:
  test: ^1.3.4
