name: barback

# Note! This version number is referenced directly in the pub source code in
# lib/src/barback.dart. Pub implicitly places a version constraint on barback to
# ensure users only select a version of barback that works with their current
# version of pub.
#
# When the minor or patch version of this is upgraded, you *must* update that
# version constraint in pub to stay in sync with this.
version: 0.15.2+2

author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  An asset build system.

  Given a set of input files and a set of transformations (think compilers,
  preprocessors and the like), will automatically apply the appropriate
  transforms and generate output files. When inputs are modified, automatically
  runs the transforms that are affected.

  Runs transforms asynchronously and in parallel when possible to maximize
  responsiveness.
dependencies:
  path: ">=0.9.0 <2.0.0"
  pool: ">=1.0.0 <2.0.0"
  source_span: ">=1.0.0 <2.0.0"
  stack_trace: ">=0.9.1 <2.0.0"
  collection: ">=0.9.1 <2.0.0"
dev_dependencies:
  scheduled_test: ">=0.9.0 <0.11.0"
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.0.1 <2.0.0"
