name: observatory
version: 1.6.0-dev.1
transformers:
- polymer:
    entry_points:
    - web/index.html
    inline_stylesheets:
      lib/src/elements/css/shared.css: false
- $dart2js:
    suppressWarnings: false
    $exclude: web/main.dart
    commandLineOptions: [--show-package-warnings]
dependencies:
  args: any
  polymer: any
  unittest: any
  usage: any
dependency_overrides:
  analyzer:
    path: ../../third_party/observatory_pub_packages/analyzer
  args:
    path: ../../third_party/observatory_pub_packages/args
  barback:
    path: ../../third_party/observatory_pub_packages/barback
  browser:
    path: ../../third_party/observatory_pub_packages/browser
  cli_util:
    path: ../../third_party/observatory_pub_packages/cli_util
  code_transformers:
    path: ../../third_party/observatory_pub_packages/code_transformers
  collection:
    path: ../../third_party/observatory_pub_packages/collection
  csslib:
    path: ../../third_party/observatory_pub_packages/csslib
  dart_style:
    path: ../../third_party/observatory_pub_packages/dart_style
  glob:
    path: ../../third_party/observatory_pub_packages/glob
  html5lib:
    path: ../../third_party/observatory_pub_packages/html5lib
  initialize:
    path: ../../third_party/observatory_pub_packages/initialize
  logging:
    path: ../../third_party/observatory_pub_packages/logging
  matcher:
    path: ../../third_party/observatory_pub_packages/matcher
  observe:
    path: ../../third_party/observatory_pub_packages/observe
  path:
    path: ../../third_party/observatory_pub_packages/path
  polymer:
    path: ../../third_party/observatory_pub_packages/polymer
  polymer_expressions:
    path: ../../third_party/observatory_pub_packages/polymer_expressions
  pool:
    path: ../../third_party/observatory_pub_packages/pool
  smoke:
    path: ../../third_party/observatory_pub_packages/smoke
  source_maps:
    path: ../../third_party/observatory_pub_packages/source_maps
  source_span:
    path: ../../third_party/observatory_pub_packages/source_span
  stack_trace:
    path: ../../third_party/observatory_pub_packages/stack_trace
  string_scanner:
    path: ../../third_party/observatory_pub_packages/string_scanner
  template_binding:
    path: ../../third_party/observatory_pub_packages/template_binding
  unittest:
    path: ../../third_party/observatory_pub_packages/unittest
  usage:
    path: ../../third_party/observatory_pub_packages/usage
  utf:
    path: ../../third_party/observatory_pub_packages/utf
  watcher:
    path: ../../third_party/observatory_pub_packages/watcher
  web_components:
    path: ../../third_party/observatory_pub_packages/web_components
  when:
    path: ../../third_party/observatory_pub_packages/when
  which:
    path: ../../third_party/observatory_pub_packages/which
  yaml:
    path: ../../third_party/observatory_pub_packages/yaml
