language: dart
dart:
  - dev
cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.pub-cache/hosted
    - node_modules
before_install:
  - test "$ANALYZER" == stable || ./tool/override_analyzer_dependency.sh
  - pub global activate dart_coveralls
  - export CHROME_CANARY_BIN=`./tool/get_chrome_canary.sh`
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - nvm install 5.5.0
  - npm install
script:
  - if [[ -z "$TEST" ]]; then ./tool/presubmit.sh ; fi
  - if [[ "$TEST" == coverage ]]; then ./tool/build_sdk.sh && ./tool/coverage.sh ; fi
  - if [[ "$TEST" == transformer ]]; then ./tool/transformer_test.sh ; fi
  - if [[ "$TEST" == node ]]; then ./tool/node_test.sh ; fi
env:
  - ANALYZER=stable
  - ANALYZER=master
  - TEST=coverage
  - TEST=transformer
  - TEST=node
matrix:
  allow_failures:
    - env: ANALYZER=master
    - env: TEST=transformer
