name: dev_compiler
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  _js_interop_checks:
    path: ../_js_interop_checks
  args: any
  bazel_worker: any
  build_integration:
    path: ../build_integration
  cli_util: any
  front_end:
    path: ../front_end
  kernel:
    path: ../kernel
  meta:
    path: ../meta
  path: any
  source_maps: any
  source_span: any
  vm:
    path: ../vm

dev_dependencies:
  analyzer:
    path: ../analyzer
  expect:
    path: ../expect
  js:
    path: ../js
  modular_test:
    path: ../modular_test
  package_config: any
  pedantic: ^1.8.0
  pub_semver: any
  sourcemap_testing:
    path: ../sourcemap_testing
  stack_trace: any
  test: any
  testing:
    path: ../testing
