name: dev_compiler
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  _js_interop_checks:
    path: ../_js_interop_checks
  args: any
  async: any
  bazel_worker: any
  build_integration:
    path: ../build_integration
  cli_util: any
  front_end:
    path: ../front_end
  kernel:
    path: ../kernel
  meta:
    path: ../meta
  path: any
  pedantic: ^1.11.0
  source_maps: any
  source_span: any

dev_dependencies:
  browser_launcher: ^0.1.9
  expect:
    path: ../expect
  http_multi_server:
    path: ../../third_party/pkg/http_multi_server
  js:
    path: ../js
  modular_test:
    path: ../modular_test
  package_config: any
  sourcemap_testing:
    path: ../sourcemap_testing
  stack_trace: any
  shelf:
    path: ../../third_party/pkg/shelf
  test: any
  testing:
    path: ../testing
  vm:
    path: ../vm
  webkit_inspection_protocol: ^0.7.4

