name: dev_compiler
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  _fe_analyzer_shared: any
  _js_interop_checks:
    path: ../_js_interop_checks
  args: any
  async: any
  bazel_worker: any
  build_integration:
    path: ../build_integration
  collection: ^1.15.0
  front_end:
    path: ../front_end
  kernel:
    path: ../kernel
  meta: any
  path: any
  source_maps: any
  source_span: any

dev_dependencies:
  browser_launcher: ^1.0.0
  expect:
    path: ../expect
  http_multi_server: any
  js: any
  lints: ^1.0.0
  modular_test:
    path: ../modular_test
  package_config: any
  sourcemap_testing:
    path: ../sourcemap_testing
  stack_trace: any
  shelf: any
  test: any
  testing:
    path: ../testing
  vm:
    path: ../vm
  webkit_inspection_protocol: ^1.0.0

dependency_overrides:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  js:
    path: ../js
  meta:
    path: ../meta
  shelf:
    path: ../../third_party/pkg/shelf
  http_multi_server:
    path: ../../third_party/pkg/http_multi_server
