name: scheduled_test
version: 0.10.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A package for writing readable tests of asynchronous behavior.

  This package works by building up a queue of asynchronous tasks called a
  "schedule", then executing those tasks in order. This allows the tests to
  read like synchronous, linear code, despite executing asynchronously.

dependencies:
  http: ">=0.9.0 <0.10.0"
  path: ">=0.9.0 <2.0.0"
  stack_trace: ">=0.9.1 <0.10.0"
  unittest: ">=0.9.0 <0.11.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
