name: observatory
version: 0.2.1
dependencies:
  polymer: '>= 0.10.0'
transformers:
- polymer:
    entry_points: 
      - web/index.html
      - web/index_devtools.html
- $dart2js:
    suppressWarnings: false
    $exclude: web/main.dart
