name: template_binding
version: 0.13.0+1
author: Polymer.dart Team <web-ui-dev@dartlang.org>
description: >
  Extends the capabilities of the HTML Template Element by enabling it to
  create, manage, and remove instances of content bound to data defined in Dart.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  observe: ">=0.11.0 <0.13.0"
  web_components: ">=0.7.0 <0.9.0"
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
environment:
  sdk: ">=1.2.0 <2.0.0"
