name: browser
version: 0.9.0
authors: ["Dart Team <misc@dartlang.org>"]
homepage: http://www.dartlang.org
description: >
 The bootstrap dart.js script for Dart apps running in the browser.
environment:
  sdk: ">=1.0.0 <2.0.0"
