name: watcher
version: 0.9.4
author: Dart Team <misc@dartlang.org>
homepage: http://www.dartlang.org
description: >
  A file system watcher. It monitors changes to contents of directories and
  sends notifications when files have been added, removed, or modified.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  path: '>=0.9.0 <2.0.0'
  stack_trace: '>=0.9.1 <2.0.0'
dev_dependencies:
  scheduled_test: '>=0.9.3 <0.12.0'
  unittest: '>=0.9.2 <0.12.0'
environment:
  sdk: ">=1.6.0 <2.0.0"
