name: watcher
version: 0.9.4-dev
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A file watcher. It monitors for changes to contents of directories and
  notifies you when files have been added, removed, or modified.
dependencies:
  path: ">=0.9.0 <2.0.0"
  stack_trace: ">=0.9.1 <2.0.0"
dev_dependencies:
  scheduled_test: ">=0.9.3-dev <0.11.0"
  unittest: ">=0.9.2 <0.10.0"
environment:
  sdk: ">=1.6.0 <2.0.0"
