name: analysis_testing
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: A set of libraries for testing Analysis services and server
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analyzer: '>=0.19.0 <1.0.0'
  typed_mock: '>=0.0.4 <0.1.0'
  unittest: '>=0.10.0 <0.12.0'
