name: mock
version: 0.10.0+1
author: Dart Team <misc@dartlang.org>
description: A library for mocking classes
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://api.dartlang.org/docs/pkg/mock
dependencies:
  matcher: '>=0.10.0 <0.11.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
