name: http_parser
version: 0.0.2+4
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A platform-independent package for parsing and serializing HTTP formats.
dependencies:
  crypto: ">=0.9.0 <0.10.0"
  collection: ">=0.9.1 <0.10.0"
  string_scanner: ">=0.0.0 <0.2.0"
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
environment:
  sdk: ">=1.2.0 <2.0.0"
