name: analysis_server
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: A server that performs analysis of Dart code over character streams using JSON-RPC encoded information.
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  analyzer: '>=0.25.3-alpha.0 <0.26.0'
  args: '>=0.13.0 <0.14.0'
  dart_style: '>=0.1.7 <0.2.0'
  logging: any
  path: any
  plugin: <0.2.0
  watcher: any
  yaml: any
dev_dependencies:
  html: any
  mock: '>=0.11.0 <0.12.0'
  test_reflective_loader: '>=0.0.3 <0.1.0'
  typed_mock: '>=0.0.4 <1.0.0'
  unittest: '>=0.11.4 <0.12.0'
