name: analysis_server
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: any
  analyzer_plugin: any
  args: any
  charcode: any
  convert: any
  crypto: any
  dart_style: any
  front_end: any
  linter: any
  logging: any
  meta: any
  pub_semver: any
  source_span: any
  stream_channel: any
  package_config: any
  path: any
  tflite_native: any
  watcher: any
  yaml: any

dev_dependencies:
  analysis_tool: any
  html: any
  http: any
  pedantic: ^1.8.0
  test_reflective_loader: any
  test: any
