name: analysis_server
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  analyzer: any
  analyzer_plugin: any
  args: any
  cli_util: any
  collection: any
  convert: any
  crypto: any
  dart_style: any
  html: any
  intl: any
  linter: any
  meta: any
  stream_channel: any
  telemetry:
    path: ../telemetry
  test: any
  path: any
  tflite_native: any
  watcher: any
  yaml: any

dev_dependencies:
  analysis_tool: any
  http: any
  logging: any
  matcher: any
  mockito: any
  pedantic: ^1.9.0
  test_reflective_loader: any
