name: analysis_server
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  _fe_analyzer_shared: any
  analyzer: any
  analyzer_plugin: any
  args: any
  collection: any
  convert: any
  crypto: any
  dart_style: any
  html: any
  http: any
  linter: any
  meta: any
  path: any
  stream_channel: any
  telemetry: any
  test: any
  watcher: any
  yaml: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  analyzer_utilities: any
  cli_util: any
  lints: any
  logging: any
  matcher: any
  test_reflective_loader: any
