name: analysis_server
version: 0.1.1-dev
author: Dart Team <misc@dartlang.org>
description: A server that performs analysis of Dart code over character streams using JSON-RPC encoded information.
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  analyzer: ^0.30.0
  args: '>=0.13.0 <0.14.0'
  dart_style: '^1.0.6'
  isolate: '>=0.2.2 <2.0.0'
  linter: ^0.1.16
  logging: any
  package_config: '>=0.1.5 <2.0.0'
  path: any
  plugin: ^0.2.0
  watcher: any
  yaml: any
dev_dependencies:
  html: any
  test_reflective_loader: ^0.1.0
  typed_mock: '>=0.0.4 <1.0.0'
  test: ^0.12.17
