name: analyzer_cli
description: Command line interface for the Dart Analyzer.

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: "^2.7.0"

dependencies:
  analyzer:
    path: ../analyzer
  args: '>=0.13.0 <2.0.0'
  bazel_worker: ^0.1.0
  collection: ^1.14.1
  convert: any
  linter: ^0.1.16
  meta:
    path: ../meta
  path: any
  pub_semver: ^1.4.2
  yaml: any

dev_dependencies:
  pedantic: ^1.9.0
  protobuf: ^0.13.0
  test_reflective_loader: ^0.1.8
  test: ^1.0.0
