name: analyzer_cli
description: Command line interface for the Dart Analyzer.

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: ^3.7.0

resolution: workspace

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  analyzer: any
  args: any
  linter: any
  meta: any
  path: any
  yaml: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  analyzer_testing: any
  lints: any
  pub_semver: any
  test_reflective_loader: any
  test: any
