name: analyzer_experimental
author: Dart Team <misc@dartlang.org>
description: Experimental static analyzer for Dart.
homepage: http://www.dartlang.org
dependencies:
  args: any
  logging: any
  pathos: any
dev_dependencies:
  unittest: any
