name: linter
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

description: >-
  The implementation of the lint rules supported by the analyzer framework.
  This package is not intended to be used directly.

environment:
  sdk: ^3.3.0

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  analyzer: any
  collection: any
  meta: any
  path: any
  pub_semver: any
  source_span: any
  yaml: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  analyzer_utilities: any
  args: any
  cli_util: any
  http: any
  lints: any
  test: any
  test_descriptor: any
  test_reflective_loader: any
