# This pubspec is currently mainly used to make it easier to develop on dart2js
# by making it a standalone package.
name: compiler
#version: do-not-upload
dependencies:
  package_config: '>=0.1.1 <2.0.0'
  pub_semver: ^1.2.1
  js:
    path: ../js
  js_ast:
    path: ../js_ast
  js_runtime:
    path: ../../sdk/lib/_internal/js_runtime
  kernel:
    path: ../../pkg/kernel
  sdk_library_metadata:
    path: ../../sdk/lib/_internal/sdk_library_metadata
  dart2js_info:
    path: ../../third_party/pkg/dart2js_info
  lookup_map:
    path: ../lookup_map
  front_end:
    path: ../front_end
dependency_overrides:
  front_end:
    path: ../front_end
  analyzer:
    path: ../analyzer
  kernel:
    path: ../../pkg/kernel

# Uncomment if running gclient, so you can depend directly on the downloaded
# versions of dart2js's transitive dependencies:
#
# dependency_overrides:
#   package_config:
#     path: ../../third_party/pkg_tested/package_config
#   path:
#     path: ../../third_party/pkg/path
#   charcode:
#     path: ../../third_party/pkg/charcode
#   collection:
#     path: ../../third_party/pkg/collection
#   crypto:
#     path: ../../third_party/pkg/crypto
#   http_parser:
#     path: ../../third_party/pkg/http_parser
#   args:
#     path: ../../third_party/pkg/args
#   shelf:
#     path: ../../third_party/pkg/shelf
#   yaml:
#     path: ../../third_party/pkg/yaml
