name: logging
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
documentation: http://api.dartlang.org/docs/pkg/logging
description: >
 Provides APIs for debugging and error logging. This library introduces
 abstractions similar to those used in other languages, such as the Closure JS
 Logger and java.util.logging.Logger.

dependencies:
  unittest:
    sdk: unittest
