name: logging
version: 0.9.1+2
author: Dart Team <misc@dartlang.org>
description: >
  Provides APIs for debugging and error logging. This library introduces
  abstractions similar to those used in other languages, such as the Closure
  JS Logger and java.util.logging.Logger.
homepage: https://pub.dartlang.org/packages/logging
environment:
  sdk: '>=1.5.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
