name: http
version: 0.9.2+3
author: "Dart Team <misc@dartlang.org>"
homepage: https://pub.dartlang.org/packages/http
description: A composable, Future-based API for making HTTP requests.
dependencies:
  path: ">=0.9.0 <2.0.0"
  stack_trace: ">=0.9.1 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.1.0 <2.0.0"
