name: http
version: 0.9.0
author: "Dart Team <misc@dartlang.org>"
homepage: https://pub.dartlang.org/packages/http
description: A composable, Future-based API for making HTTP requests.
dependencies:
  path: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
