name: dart_internal
version: 0.2.4
repository: https://github.com/dart-lang/sdk/tree/master/pkg/dart_internal
description: >-
  This package is not intended for wide use. It provides a temporary API to
  solve the problem: "Given an object some generic type A, how do I construct an
  instance of generic type B with the same type argument(s)?"

environment:
  # Restrict the upper bound so that we can remove support for this in a later
  # version of the SDK without it being a breaking change.
  sdk: ">=2.12.0 <2.18.0"
