name: stack_trace
version: 0.9.2-dev
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A package for manipulating stack traces and printing them readably.

dependencies:
  path: ">=1.0.0-rc.1 <2.0.0"

dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
