name: intl
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
documentation: http://api.dartlang.org/docs/pkg/intl.html
description: >
  Contains code to deal with internationalized/localized
  messages, date and number formatting and parsing,
  bi-directional text, and other internationalization issues.
dependencies:
  unittest:
    sdk: unittest
