name: kernel
version: 0.3.0-alpha.1.1
author: Dart Team <misc@dartlang.org>
description: Dart IR (Intermediate Representation)
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/kernel
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  path: ^1.3.9
  args: '>=0.13.4 <2.0.0'
  logging: ^0.11.2
  package_config: ^1.0.0
dev_dependencies:
  analyzer: ^0.30.0
  front_end: 0.1.0-alpha.4.1
  test: ^0.12.15+6
  stack_trace: ^1.6.6
  ansicolor: ^0.0.9
  testing:
    git:
      url: https://github.com/peter-ahe-google/testing.git
      ref: 2e196d5
