name: kernel
dependencies:
  # We import some of the analyzer's internal files, so lock the patch version.
  analyzer: 0.27.4-alpha.9
  path: ^1.3.9
  args: ^0.13.4
  logging: ^0.11.2
dev_dependencies:
  test: ^0.12.13
