name: kernel
# Currently, kernel API is not stable and users should
# not depend on semver semantics when depending on this package.
version: 0.3.0
author: Dart Team <misc@dartlang.org>
description: Dart IR (Intermediate Representation)
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/kernel
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  path: ^1.3.9
  args: '>=0.13.4 <2.0.0'
  logging: ^0.11.2
  package_config: ^1.0.0
dev_dependencies:
  analyzer: '>=0.31.0 <0.33.0'
  front_end: 0.1.0
  test: ^0.12.15+6
  stack_trace: ^1.6.6
  ansicolor: ^0.0.9
  test_reflective_loader: ^0.1.0
  testing:
    git:
      url: https://github.com/peter-ahe-google/testing.git
      ref: 2e196d5
