name: kernel
# Currently, kernel API is not stable and users should
# not depend on semver semantics when depending on this package.
version: 0.3.11
author: Dart Team <misc@dartlang.org>
description: Dart IR (Intermediate Representation)
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/kernel
environment:
  sdk: '>=2.0.0-dev.48.0 <3.0.0'
dependencies:
  path: ^1.3.9
  args: '>=0.13.4 <2.0.0'
dev_dependencies:
  expect:
    path: ../expect
  front_end: 0.1.11
  test: ^1.3.4
  stack_trace: ^1.6.6
  test_reflective_loader: ^0.1.0
  testing:
    path: ../testing
