name: analyzer_plugin
description: A framework and support code for building plugins for the analysis server.
version: 0.3.0
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/analyzer_plugin

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  analyzer: '^0.39.12'
  charcode: '^1.1.0'
  dart_style: '^1.2.0'
  html: '>=0.13.1 <0.15.0'
  meta: ^1.0.2
  path: '^1.4.1'
  pub_semver: '^1.3.2'

dev_dependencies:
  analysis_tool:
    path: ../analysis_tool
  front_end:
    path: ../front_end
  test_reflective_loader: ^0.1.8
  test: ^1.0.0
