name: analyzer_plugin
description: A framework and support code for building plugins for the analysis server.
version: 0.9.0
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/analyzer_plugin

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  collection: ^1.15.0
  dart_style: ^2.2.1
  pub_semver: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  analyzer_utilities:
    path: ../analyzer_utilities
  html: ^0.15.0
  path: ^1.8.0
  test_reflective_loader: ^0.2.0
  test: ^1.16.6
