name: analyzer_plugin
description: A framework and support code for building plugins for the analysis server.
version: 0.11.3
repository: https://github.com/dart-lang/sdk/tree/main/pkg/analyzer_plugin

environment:
  sdk: '^3.0.0'

dependencies:
  analyzer: ^6.0.0
  collection: ^1.15.0
  dart_style: ^2.2.1
  pub_semver: ^2.1.0
  yaml: ^3.1.0

# We use 'any' version constraints here as we get our package versions from
# the dart-lang/sdk repo's DEPS file. Note that this is a special case; the
# best practice for packages is to specify their compatible version ranges.
# See also https://dart.dev/tools/pub/dependencies.
dev_dependencies:
  analyzer_utilities: any
  lints: any
  linter: any
  meta: any
  path: any
  test_reflective_loader: any
  test: any
