name: native_stack_traces
description: Utilities for working with non-symbolic stack traces.
version: 0.2.1

homepage: https://github.com/dart-lang/sdk/tree/master/pkg/native_stack_traces

environment:
  sdk: '>=2.7.1 <3.0.0'

executables:
  decode:

dependencies:
  args: ^1.5.2
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.8.0
