name: native_stack_traces
version: 0.4.5
description: Utilities for working with non-symbolic stack traces.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/native_stack_traces

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  decode:

dependencies:
  args: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  lints: any
