name: native_stack_traces
description: Utilities for working with non-symbolic stack traces.
version: 0.4.0

homepage: https://github.com/dart-lang/sdk/tree/master/pkg/native_stack_traces

environment:
  sdk: '>=2.12.0-0 <3.0.0'

executables:
  decode:

dependencies:
  args: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
