name: analysis_server_plugin
description: A framework and support code for building plugins for the analysis server.
version: 0.3.11
repository: https://github.com/dart-lang/sdk/tree/main/pkg/analysis_server_plugin

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  # See the release policy for managing this dependency at
  # pkg/analyzer/doc/implementation/releasing.md.
  analyzer: 11.0.0
  analyzer_plugin: 0.14.5
  meta: ^1.16.0
  yaml: ^3.1.0
  yaml_edit: ^2.2.0

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  analyzer_testing: any
  analyzer_utilities: any
  async: any
  lints: any
  path: any
  test_reflective_loader: any
  test: any

