name: analysis_server_plugin
description: A framework and support code for building plugins for the analysis server.
version: 0.1.0-dev
repository: https://github.com/dart-lang/sdk/tree/main/pkg/analysis_server_plugin

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  _fe_analyzer_shared: ^77.0.0
  analyzer: ^7.0.0
  analyzer_plugin: ^0.12.0
  meta: ^1.16.0

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  async: any
  lints: any
  test_reflective_loader: any
  test: any

# These dependency overrides are present in order to allow publishing this
# package. Otherwise, `dart pub publish` complains, even though they are dev
# dependencies.
dependency_overrides:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  analyzer:
    path: ../analyzer
  analyzer_plugin:
    path: ../analyzer_plugin
  analyzer_utilities:
    path: ../analyzer_utilities
  args:
    path: ../../third_party/pkg/args
  async:
    path: ../../third_party/pkg/async
  boolean_selector:
    path: ../../third_party/pkg/boolean_selector
  cli_util:
    path: ../../third_party/pkg/cli_util
  clock:
    path: ../../third_party/pkg/clock
  collection:
    path: ../../third_party/pkg/collection
  convert:
    path: ../../third_party/pkg/convert
  crypto:
    path: ../../third_party/pkg/crypto
  dart_style:
    path: ../../third_party/pkg/dart_style
  file:
    path: ../../third_party/pkg/file/packages/file
  frontend_server_client:
    path: ../../third_party/pkg/webdev/frontend_server_client
  glob:
    path: ../../third_party/pkg/glob
  http:
    path: ../../third_party/pkg/http/pkgs/http
  http_multi_server:
    path: ../../third_party/pkg/http_multi_server
  http_parser:
    path: ../../third_party/pkg/http_parser
  intl:
    path: ../../third_party/pkg/intl
  js:
    path: ../js
  language_server_protocol:
    path: ../../third_party/pkg/language_server_protocol
  linter:
    path: ../linter
  lints:
    path: ../../third_party/pkg/lints
  logging:
    path: ../../third_party/pkg/logging
  matcher:
    path: ../../third_party/pkg/matcher
  memory_usage:
    path: ../../third_party/pkg/leak_tracker/pkgs/memory_usage
  meta:
    path: ../meta
  mime:
    path: ../../third_party/pkg/tools/pkgs/mime
  package_config:
    path: ../../third_party/pkg/package_config
  path:
    path: ../../third_party/pkg/path
  pool:
    path: ../../third_party/pkg/pool
  pub_semver:
    path: ../../third_party/pkg/pub_semver
  server_plugin:
    path: ../server_plugin
  shelf:
    path: ../../third_party/pkg/shelf/pkgs/shelf
  shelf_packages_handler:
    path: ../../third_party/pkg/shelf/pkgs/shelf_packages_handler
  shelf_static:
    path: ../../third_party/pkg/shelf/pkgs/shelf_static
  shelf_web_socket:
    path: ../../third_party/pkg/shelf/pkgs/shelf_web_socket
  source_map_stack_trace:
    path: ../../third_party/pkg/tools/pkgs/source_map_stack_trace
  source_maps:
    path: ../../third_party/pkg/source_maps
  source_span:
    path: ../../third_party/pkg/source_span
  stack_trace:
    path: ../../third_party/pkg/stack_trace
  stream_channel:
    path: ../../third_party/pkg/stream_channel
  string_scanner:
    path: ../../third_party/pkg/string_scanner
  telemetry:
    path: ../telemetry
  term_glyph:
    path: ../../third_party/pkg/term_glyph
  test:
    path: ../../third_party/pkg/test/pkgs/test
  test_api:
    path: ../../third_party/pkg/test/pkgs/test_api
  test_core:
    path: ../../third_party/pkg/test/pkgs/test_core
  test_descriptor:
    path: ../../third_party/pkg/test_descriptor
  test_reflective_loader:
    path: ../../third_party/pkg/test_reflective_loader
  typed_data:
    path: ../../third_party/pkg/typed_data
  unified_analytics:
    path: ../../third_party/pkg/tools/pkgs/unified_analytics
  usage:
    path: ../../third_party/pkg/usage
  vm_service:
    path: ../vm_service
  watcher:
    path: ../../third_party/pkg/watcher
  web_socket_channel:
    path: ../../third_party/pkg/web_socket_channel
  webkit_inspection_protocol:
    path: ../../third_party/pkg/webkit_inspection_protocol
  yaml:
    path: ../../third_party/pkg/yaml
  yaml_edit:
    path: ../../third_party/pkg/yaml_edit
