name: analyzer_utilities
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: any
  html: any
  meta: any
  path: any
  test: any

dev_dependencies:
  lints: any
