name: dartfix
version: 0.1.7
description:
  A tool for migrating Dart source to newer versions of the Dart SDK
  and fixing common issues.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/dartfix
environment:
  sdk: '>=2.8.0 <3.0.0'

# Add the bin/dartfix.dart script to the scripts pub installs.
executables:
  dartfix:

dependencies:
  # Pin to an exact version of analysis_server_client because the edit.dartfix
  # protocol is experimental and will continue to evolve.
  analysis_server_client: '>=1.1.3 <1.1.4'
  args: ^1.4.0
  cli_util: ^0.1.3
  path: ^1.7.0
  pub_semver: ^1.4.4

dev_dependencies:
  analyzer: ^0.39.0
  pedantic: ^1.8.0
  test: ^1.14.2
