name: dartfix
version: 0.1.5-dev
author: Dart Team <misc@dartlang.org>
description:
  A tool for migrating Dart source to newer versions of the Dart SDK
  and fixing common issues.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/dartfix
environment:
  sdk: '>=2.3.0 <3.0.0'

# Add the bin/dartfix.dart script to the scripts pub installs.
executables:
  dartfix:

dependencies:
  # pin to an exact version of analysis_server_client because the edit.dartfix protocol
  # is experimental and will continue to evolve
  analysis_server_client: 1.1.2
  args: ^1.4.0
  cli_util: ^0.1.3
  path: ^1.6.0
  pub_semver: ^1.4.2

dev_dependencies:
  analyzer: ^0.37.0
  pedantic: ^1.8.0
  test: ^1.3.0

dependency_overrides:
  analysis_server_client:
    path: ../analysis_server_client
