name: expect
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
description: >-
 Expect is used for tests that do not want to make use of the
 Dart unit test library - for example, the core language tests.
 Third parties are discouraged from using this, and should use
 the expect() function in the unit test library instead for
 test assertions.

environment:
  sdk: '>=2.0.0'

dependencies:
  meta:
    path: ../meta
