name: expect
version: 0.9.1-dev
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
 Expect is used for tests that do not want to make use of the
 Dart unit test library - for example, the core language tests.
 Third parties are discouraged from using this, and should use
 the expect() function in the unit test library instead for
 test assertions.
environment:
  sdk: ">=0.8.10+6 <2.0.0"
