name: vm_service
description: >-
  A library to communicate with a service implementing the Dart VM
  service protocol.
version: 5.5.0

homepage: https://github.com/dart-lang/sdk/tree/master/pkg/vm_service

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.0.2

dev_dependencies:
  async: ^2.0.0
  markdown: ^2.0.0
  mockito: ^4.0.0
  path: ^1.0.0
  pedantic: ^1.7.0
  pub_semver: ^1.0.0
  test: ^1.0.0
