name: vm_service
version: 8.3.0
description: >-
  A library to communicate with a service implementing the Dart VM
  service protocol.

repository: https://github.com/dart-lang/sdk/tree/main/pkg/vm_service

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:

dev_dependencies:
  async: ^2.5.0
  expect: any
  lints: any
  markdown: ^5.0.0
  mockito: any
  path: ^1.8.0
  process: ^4.0.0
  pub_semver: ^2.0.0
  test: ^1.16.0
  test_package:
    path: 'test/test_package'
