name: record_use
description: >
  The serialization logic and API for the usage recording SDK feature.
version: 0.2.0
repository: https://github.com/dart-lang/sdk/tree/main/pkg/record_use

environment:
  sdk: ^3.4.0

dependencies:
  collection: ^1.18.0
  pub_semver: ^2.1.4

dev_dependencies:
  dart_flutter_team_lints: any
  lints: any
  test: any
