name: js
version: 0.6.3-nullsafety.3
description: Annotations to create static Dart interfaces for JavaScript APIs.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/js

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
