name: js
version: 0.6.3-nullsafety
description: Annotations to create static Dart interfaces for JavaScript APIs.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/js

environment:
  sdk: '>=2.9.0-18.0 <2.9.0'

dev_dependencies:
  pedantic: ^1.9.0
