name: json
description: >
  Easy encoding and decoding of JSON maps (maps of type `Map<String, Object?>`).
  Uses a macro that auto-generates a `fromJson` decoding constructor and a
  `toJson` encoding method.

repository: https://github.com/dart-lang/sdk/tree/main/pkg/json
version: 0.20.0
environment:
  sdk: ^3.5.0-0
dependencies:
  macros: ^0.1.0-0
dev_dependencies:
  lints: any
  test: any
