name: _js_interop_checks
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  # Use min prerelease bound to get the latest formatter changes.
  sdk: '^3.8.0'

resolution: workspace

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  _fe_analyzer_shared: any
  front_end: any
  kernel: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  lints: any
