name: modular_test
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
description: >
 Small framework to test modular pipelines.
 This is used within the Dart SDK to define and validate modular tests, and to
 execute them using the modular pipeline of different SDK tools.
environment:
  sdk: ">=2.2.1 <3.0.0"

dependencies:
  package_config: ^1.0.5
  yaml: ^2.1.15

dev_dependencies:
  args: any
  test: any
