name: sdk_tools
description: Internal tools for building and working on the sdk.

environment:
  sdk: ^3.5.0

resolution: workspace

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

dependencies:
  args:
  bisect_dart:
  cli_util:
  convert:
  crypto:
  glob:
  http:
  path:
  pool:
  pub_semver:
  smith:
  test_runner:
  yaml:
