name: _fe_analyzer_shared
version: 64.0.0
description: Logic that is shared between the front_end and analyzer packages.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/_fe_analyzer_shared

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.0


# We use 'any' version constraints here as we get our package versions from
# the dart-lang/sdk repo's DEPS file. Note that this is a special case; the
# best practice for packages is to specify their compatible version ranges.
# See also https://dart.dev/tools/pub/dependencies.
dev_dependencies:
  checks: any
  test: any

dependency_overrides:
  test:
    path: ../../third_party/pkg/test/pkgs/test/
  analyzer:
    path: ../analyzer
