name: meta
version: 1.1.4
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/meta
description: >
 This library contains the definitions of annotations that provide additional
 semantic information about the program being annotated. These annotations are
 intended to be used by tools to provide a better user experience.
environment:
  sdk: '>=1.12.0 <2.0.0'
