name: frontend_server
description: A resident kernel compiler
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: "^2.15.0"

dependencies:
  args: ^2.0.0
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  build_integration:
    path: ../build_integration
  compiler:
    path: ../compiler
  dev_compiler:
    path: ../dev_compiler
  front_end:
    path: ../front_end
  kernel:
    path: ../kernel
  package_config: ^2.0.0
  path: any
  usage: any
  vm:
    path: ../vm

dev_dependencies:
  mockito: any
  test: any
