name: html_import
author: "Web UI Team <web-ui-dev@dartlang.org>"
homepage: https://github.com/Polymer/HTMLImports/tree/master
description: >
  HTML Imports are a way to include and reuse HTML documents in other HTML
  documents. As <script> tags let authors include external code in their
  pages, imports let authors load full HTML resources. In particular, imports
  let authors include Custom Element definitions from external URLs.
