name: wasm_builder
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
description: Generate binary Wasm modules

environment:
  sdk: '>=2.19.0 <3.0.0'

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependency:
  lints: any
