name: linter

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  pull_request:
  push:
    branches:
      - master

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  build:
    name: ${{ matrix.linter-bot }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter-bot:
          - main
          - coverage
          - release
          - pana_baseline
          - benchmark

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: dev

      - run: dart pub get

      - name: tool/bot.sh
        env:
          LINTER_BOT: ${{ matrix.linter-bot }}
        run: ./tool/bot.sh
      - name: upload coverage
        if: matrix.linter-bot == 'coverage'
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: var/lcov.info
