# A workflow to invoke a triage automation bot.
#
# For more information, see
# https://github.com/dart-lang/ecosystem/tree/main/pkgs/sdk_triage_bot and
# https://github.com/dart-lang/sdk/blob/main/docs/Triaging-Dart-SDK-issues.md.

name: Triage Bot

# Run when an issue is created.
on:
  issues:
    types:
      - opened

# All permissions not specified are set to 'none'.
permissions:
  issues: write

jobs:
  triage_issues:
    runs-on: ubuntu-latest

    # Don't fail the workflow if there's an error below (for example, if we
    # have problems modifying an issue's labels) as that would send a failure
    # email to the user who created the issue.
    continue-on-error: true

    if: ${{ github.repository_owner == 'dart-lang' }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: dart-lang/ecosystem

      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c

      - run: dart pub get
        working-directory: pkgs/sdk_triage_bot

      # Delay 2 minutes to allow a grace period between opening or transferring
      # an issue and assigning an area- label.
      - name: sleep 2m
        run: sleep 120

      - name: triage issue
        working-directory: pkgs/sdk_triage_bot
        env:
          ISSUE_URL: ${{ github.event.issue.html_url }}
          GITHUB_TOKEN: ${{ secrets.DARTBOT_GITHUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: dart bin/triage.dart $ISSUE_URL
